influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "127.0.0.1:8083:8083"
    - "127.0.0.1:8086:8086"
    - "127.0.0.1:8090:8090"
  env_file:
    - 'env.influxdb'

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "80:3000"
  links:
    - influxdb
