#!/usr/bin/env python
import argparse
import pymongo, gridfs
import argcomplete
from sub import *
    
main_parser = argparse.ArgumentParser()
main_parser.add_argument('--dbname', type=str, nargs='?', default='toto')
main_subparsers = main_parser.add_subparsers()

collector.argparser(main_subparsers)
httpd.argparser(main_subparsers)
daemon.argparser(main_subparsers)
config.argparser(main_subparsers)
source.argparser(main_subparsers)
run.argparser(main_subparsers)

argcomplete.autocomplete(main_parser)
args = main_parser.parse_args()
with pymongo.MongoClient() as client:
    db = client[args.dbname]
    res = args.func(db, gridfs.GridFS(db), args)
    if res != None: print(res)
